### ISSUE TITLE
Bunch of "Module Not Found" Errors

### ISSUE THREAD

**Issue by Differ812** [RileyXX/TMDB-Trakt-Syncer#31]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\authTrakt.py", line 4, in <module>
    from TMDBTraktSyncer import errorLogger as EL
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\errorLogger.py", line 4, in <module>
    import selenium.webdriver
ModuleNotFoundError: No module named 'selenium'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\verifyCredentials.py", line 4, in <module>
    from TMDBTraktSyncer import authTrakt
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\authTrakt.py", line 6, in <module>
    import errorLogger as EL
ModuleNotFoundError: No module named 'errorLogger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\TMDBTraktSyncer.py", line 5, in <module>
    from TMDBTraktSyncer import verifyCredentials as VC
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\verifyCredentials.py", line 7, in <module>
    import authTrakt
ModuleNotFoundError: No module named 'authTrakt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Scripts\TMDBTraktSyncer.exe\__main__.py", line 4, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\TMDBTraktSyncer\TMDBTraktSyncer.py", line 11, in <module>
    import verifyCredentials as VC
ModuleNotFoundError: No module named 'verifyCredentials'

### Environment

Windows 11
Using PIP install method // had to do pip install TMDBTraktSyncer (python -m pip install TMDBTraktSyncer) doesnt work says python not found "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."

**Comment by RileyXX** [comment]
`Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.`

Hi, this error is due to no PATH variable added for Python. You'll need to uninstall then reinstall Python, during installation tick the box for adding Python to your systems PATH variable. 

After doing that reinstall the script with `python -m pip install TMDBTraktSyncer --upgrade` and run again with `TMDBTraktSyncer` in command prompt. 

If you try that and are still having issues paste any other relevant errors here and I'll take another look.

**Comment by Differ812** [comment]
Python was added to PATH on installation, I've reistalled it, I've added it manually even, nothing.

This must be something with the python command itself, I'll research further when I have the time.

**Comment by Differ812** [comment]
Solved the "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases." - by following this https://medium.com/@viknesh2798/how-to-fix-the-issues-while-using-python-command-in-the-command-prompt-ba56d9018c5f

still the script doesnt work and gives the same error

**Comment by RileyXX** [comment]
Sounds like it could be an issue with double Python installations. 

I would try uninstalling Python. Then go to `C:\Users\YOUR_USERNAME\AppData\Local\Programs` and delete the Python folder. After doing that go to windows start button and search `system environment variables` and open it. From the popup click `Environment Variables`. You will see two sections `User` and `System`. Under `User` variables click the PATH variable and click `Edit`. Then delete any lines with `Python` in it. Close that popup and do the same thing for the system variables section.

After doing all that reinstall Python again and make sure to tick the box for adding Python to the Path variable during install. Reinstall `TMDBTraktSyncer` and run it and see if that resolves it.

**Comment by Differ812** [comment]
> Solved the "Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases." - by following this https://medium.com/@viknesh2798/how-to-fix-the-issues-while-using-python-command-in-the-command-prompt-ba56d9018c5f
> 
> still the script doesnt work and gives the same error

now everything works as intended, but still getting the error regarding the script

also figured that disabling directly the 
![image](https://github.com/RileyXX/TMDB-Trakt-Syncer/assets/69480940/d0278b32-aee3-4202-ac33-ba7e0bdc5397)
will allow the default windows 11 command to be turned off, this is for a installation package through microsoft store, which is a hell

**Comment by Differ812** [comment]
keep in mind this whole process has been done in a brande new windows 11 install

**Comment by Differ812** [comment]
also both the "user variables" and "system variables" have Path with `C:\Users\diffe\AppData\Local\Programs\Python\Python312\Scripts\` and `C:\Users\diffe\AppData\Local\Programs\Python\Python312\`

**Comment by RileyXX** [comment]
Yeah that's odd behavior. So what errors are you getting now? 

The `ModuleNotFoundError: No module named 'selenium'` error can be solved by running `python -m pip install selenium` to install the missing module. Although this should have been installed automatically when installing TMDBTraktSyncer. Uninstalling TMDBTraktSyncer and then reinstalling it with pip should also force the packages to reinstall.

The rest of the module errors are just the local script files so it's odd that they are also giving import errors. How are you running the script? Just through command line right by running `TMDBTraktSyncer`?

**Comment by RileyXX** [comment]
I see. Glad to hear it's fixed now.

I just did a clean install with Python v3.12 and installed TMDBTraktSyncer and got the same error. I see what the issue is now. Selenium actually isn't required for TMDBTraktSyncer but for some reason it was included as an import in the `errorLogger.py` file which was causing this error. This is a bug. I will release a fix for this shortly. 

Thanks for taking the time to help troubleshoot!

**Comment by RileyXX** [comment]
This is fixed now in TMDBTraktSyncer [v1.6.4](https://github.com/RileyXX/TMDB-Trakt-Syncer/releases) or later. 

You can update using:
```
python -m pip install TMDBTraktSyncer
```
